"""Admin utility tools for managing automation API keys.

Use this script when a user loses their automation API key. Since we only store
the sha256 hash (not plaintext), we cannot retrieve the original key. Instead,
generate a new one by:

    1. Finding the user by email
    2. Revoking the old key
    3. Generating a new key
    4. Providing it to the user

For production, consider wrapping these functions in a secured admin endpoint
that requires admin authentication.

Usage:

    # In a Python shell or script with DB access:
    
    from admin_tools import admin_revoke_user_automation_key, admin_generate_new_automation_key
    from database import init_pool, close_pool
    
    async def main():
        await init_pool()
        
        # Revoke old key
        user_email = "user@example.com"
        await admin_revoke_user_automation_key(user_email)
        print(f"Revoked all keys for {user_email}")
        
        # Generate new key
        raw_key = await admin_generate_new_automation_key(
            user_email=user_email,
            label="Regenerated by admin"
        )
        print(f"New key: {raw_key}")
        print("Share this key with the user securely (e.g., via secure message)")
        
        await close_pool()
    
    asyncio.run(main())
"""

from __future__ import annotations

import hashlib
import secrets
import string
from database import get_conn


async def admin_list_user_automation_keys(user_email: str) -> list[dict]:
    """List all automation API keys for a user (for admin viewing).
    
    Args:
        user_email: Email of the user
        
    Returns:
        List of key metadata (id, label, last_4, is_active, created_at, last_used_at)
        
    Raises:
        ValueError: If user not found
    """
    async with get_conn() as conn:
        # Find user by email
        cur = await conn.execute(
            "SELECT id FROM users WHERE email = %s",
            (user_email,),
        )
        user_row = await cur.fetchone()
        if not user_row:
            raise ValueError(f"User not found: {user_email}")
        
        user_id = user_row["id"]
        
        # Get all automation keys for this user
        cur2 = await conn.execute(
            """
            SELECT id, user_id, label, last_4, is_active, created_at, last_used_at
            FROM automation_api_keys
            WHERE user_id = %s::uuid
            ORDER BY created_at DESC
            """,
            (str(user_id),),
        )
        rows = await cur2.fetchall()
        return [dict(r) for r in rows]


async def admin_revoke_user_automation_key(user_email: str, key_id: str | None = None) -> int:
    """Revoke automation API key(s) for a user.
    
    Args:
        user_email: Email of the user
        key_id: Optional specific key ID to revoke. If None, revokes ALL keys for the user.
        
    Returns:
        Number of keys revoked
        
    Raises:
        ValueError: If user not found
    """
    async with get_conn() as conn:
        # Find user by email
        cur = await conn.execute(
            "SELECT id FROM users WHERE email = %s",
            (user_email,),
        )
        user_row = await cur.fetchone()
        if not user_row:
            raise ValueError(f"User not found: {user_email}")
        
        user_id = user_row["id"]
        
        if key_id:
            # Revoke specific key
            cur2 = await conn.execute(
                """
                DELETE FROM automation_api_keys
                WHERE id = %s::uuid AND user_id = %s::uuid
                """,
                (key_id, str(user_id)),
            )
            return cur2.rowcount
        else:
            # Revoke ALL keys for this user
            cur2 = await conn.execute(
                "DELETE FROM automation_api_keys WHERE user_id = %s::uuid",
                (str(user_id),),
            )
            return cur2.rowcount


async def admin_generate_new_automation_key(
    user_email: str,
    label: str = "Regenerated by admin",
    revoke_old: bool = True,
) -> str:
    """Generate a new automation API key for a user (admin function for lost keys).
    
    Args:
        user_email: Email of the user
        label: Label for the new key
        revoke_old: If True, revoke all existing keys first
        
    Returns:
        The raw plaintext key (show to user only once)
        
    Raises:
        ValueError: If user not found
    """
    async with get_conn() as conn:
        # Find user by email
        cur = await conn.execute(
            "SELECT id FROM users WHERE email = %s",
            (user_email,),
        )
        user_row = await cur.fetchone()
        if not user_row:
            raise ValueError(f"User not found: {user_email}")
        
        user_id = user_row["id"]
        
        # Optionally revoke old keys
        if revoke_old:
            await conn.execute(
                "DELETE FROM automation_api_keys WHERE user_id = %s::uuid",
                (str(user_id),),
            )
        
        # Generate new secure key
        alphabet = string.ascii_letters + string.digits
        raw_key = ''.join(secrets.choice(alphabet) for _ in range(32))
        
        # Hash it for storage
        key_hash = hashlib.sha256(raw_key.encode()).hexdigest()
        
        # Store in DB
        await conn.execute(
            """
            INSERT INTO automation_api_keys (user_id, key_hash, label, last_4)
            VALUES (%s::uuid, %s, %s, %s)
            """,
            (str(user_id), key_hash, label, raw_key[-4:]),
        )
        
        return raw_key


async def admin_view_key_metadata_only(user_email: str) -> list[dict]:
    """View all automation keys for a user (metadata only, NO plaintext keys possible).
    
    This is safe for admins to view because:
    - We NEVER store plaintext keys, only sha256 hashes
    - Admin can see: label, last_4, when created, when last used
    - Admin CANNOT see: the full key or any way to reconstruct it
    - If user lost key, admin must revoke old and generate new one
    
    Args:
        user_email: Email of the user
        
    Returns:
        List of key metadata
        
    Raises:
        ValueError: If user not found
    """
    return await admin_list_user_automation_keys(user_email)


# ── Example admin CLI usage ────────────────────────────────────────────────────

if __name__ == "__main__":
    import asyncio
    import sys
    
    async def main():
        from database import init_pool, close_pool
        
        if len(sys.argv) < 2:
            print("Usage: python admin_tools.py <command> <email> [args]")
            print("")
            print("Commands:")
            print("  list <email>                    - List all keys for user")
            print("  revoke <email>                  - Revoke ALL keys for user")
            print("  revoke <email> <key_id>         - Revoke specific key")
            print("  generate <email>                - Generate new key (revokes old ones)")
            print("  view <email>                    - View key metadata (admin safe)")
            return
        
        await init_pool()
        
        try:
            command = sys.argv[1]
            email = sys.argv[2]
            
            if command == "list":
                keys = await admin_list_user_automation_keys(email)
                print(f"Automation keys for {email}:")
                for k in keys:
                    print(f"  [{k['id']}] {k['label']} (last_4: {k['last_4']}, active: {k['is_active']})")
                    print(f"    Created: {k['created_at']}, Last used: {k['last_used_at']}")
            
            elif command == "revoke":
                if len(sys.argv) > 3:
                    key_id = sys.argv[3]
                    count = await admin_revoke_user_automation_key(email, key_id)
                    print(f"Revoked {count} key(s)")
                else:
                    count = await admin_revoke_user_automation_key(email)
                    print(f"Revoked all {count} key(s) for {email}")
            
            elif command == "generate":
                revoke_old = True
                if len(sys.argv) > 3 and sys.argv[3] == "--keep-old":
                    revoke_old = False
                
                raw_key = await admin_generate_new_automation_key(
                    email,
                    label="Regenerated by admin",
                    revoke_old=revoke_old,
                )
                print(f"New automation API key for {email}:")
                print(f"  {raw_key}")
                print("")
                print("⚠️  Share this key with the user ONCE ONLY via secure channel (email, secure message, etc.)")
                print("⚠️  If they lose it again, you'll need to regenerate.")
                print("")
                print("For n8n, configure the header:")
                print(f"  X-API-Key: {raw_key}")
            
            elif command == "view":
                keys = await admin_view_key_metadata_only(email)
                print(f"Automation keys for {email} (metadata only):")
                for k in keys:
                    print(f"  [{k['id']}] {k['label']}")
                    print(f"    Last 4 chars: {k['last_4']}")
                    print(f"    Active: {k['is_active']}")
                    print(f"    Created: {k['created_at']}")
                    print(f"    Last used: {k['last_used_at']}")
            
            else:
                print(f"Unknown command: {command}")
        
        except ValueError as e:
            print(f"Error: {e}", file=sys.stderr)
            sys.exit(1)
        except Exception as e:
            print(f"Error: {e}", file=sys.stderr)
            sys.exit(1)
        finally:
            await close_pool()
    
    asyncio.run(main())
